/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};
/******/
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/
/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId]) {
/******/ 			return installedModules[moduleId].exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			i: moduleId,
/******/ 			l: false,
/******/ 			exports: {}
/******/ 		};
/******/
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
/******/
/******/ 		// Flag the module as loaded
/******/ 		module.l = true;
/******/
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/
/******/
/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;
/******/
/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;
/******/
/******/ 	// define getter function for harmony exports
/******/ 	__webpack_require__.d = function(exports, name, getter) {
/******/ 		if(!__webpack_require__.o(exports, name)) {
/******/ 			Object.defineProperty(exports, name, { enumerable: true, get: getter });
/******/ 		}
/******/ 	};
/******/
/******/ 	// define __esModule on exports
/******/ 	__webpack_require__.r = function(exports) {
/******/ 		if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
/******/ 			Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
/******/ 		}
/******/ 		Object.defineProperty(exports, '__esModule', { value: true });
/******/ 	};
/******/
/******/ 	// create a fake namespace object
/******/ 	// mode & 1: value is a module id, require it
/******/ 	// mode & 2: merge all properties of value into the ns
/******/ 	// mode & 4: return value when already ns object
/******/ 	// mode & 8|1: behave like require
/******/ 	__webpack_require__.t = function(value, mode) {
/******/ 		if(mode & 1) value = __webpack_require__(value);
/******/ 		if(mode & 8) return value;
/******/ 		if((mode & 4) && typeof value === 'object' && value && value.__esModule) return value;
/******/ 		var ns = Object.create(null);
/******/ 		__webpack_require__.r(ns);
/******/ 		Object.defineProperty(ns, 'default', { enumerable: true, value: value });
/******/ 		if(mode & 2 && typeof value != 'string') for(var key in value) __webpack_require__.d(ns, key, function(key) { return value[key]; }.bind(null, key));
/******/ 		return ns;
/******/ 	};
/******/
/******/ 	// getDefaultExport function for compatibility with non-harmony modules
/******/ 	__webpack_require__.n = function(module) {
/******/ 		var getter = module && module.__esModule ?
/******/ 			function getDefault() { return module['default']; } :
/******/ 			function getModuleExports() { return module; };
/******/ 		__webpack_require__.d(getter, 'a', getter);
/******/ 		return getter;
/******/ 	};
/******/
/******/ 	// Object.prototype.hasOwnProperty.call
/******/ 	__webpack_require__.o = function(object, property) { return Object.prototype.hasOwnProperty.call(object, property); };
/******/
/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";
/******/
/******/
/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(__webpack_require__.s = "./src/service-worker.ts");
/******/ })
/************************************************************************/
/******/ ({

/***/ "./src/node_modules/@sapper/service-worker.js":
/*!****************************************************!*\
  !*** ./src/node_modules/@sapper/service-worker.js ***!
  \****************************************************/
/*! exports provided: timestamp, files, assets, shell, routes */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"timestamp\", function() { return timestamp; });\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"files\", function() { return files; });\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"assets\", function() { return files; });\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"shell\", function() { return shell; });\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"routes\", function() { return routes; });\n// This file is generated by Sapper — do not edit it!\nconst timestamp = 1609352782994;\n\nconst files = [\n\t\"/service-worker-index.html\",\n\t\"/black-square.jpg\",\n\t\"/favicon.png\",\n\t\"/logo-192.png\",\n\t\"/logo-512.png\",\n\t\"/logo-contur.svg\",\n\t\"/logo.svg\",\n\t\"/logo1.svg\",\n\t\"/logo2.svg\",\n\t\"/logo3.svg\",\n\t\"/logo_circle_contur.svg\",\n\t\"/manifest.json\",\n\t\"/square.png\"\n];\n // legacy\n\nconst shell = [\n\t\"/client/3ccd9cc38a7fcdd5e3bf/0.0.js\",\n\t\"/client/3ccd9cc38a7fcdd5e3bf/1.1.js\",\n\t\"/client/3ccd9cc38a7fcdd5e3bf/2.2.js\",\n\t\"/client/3ccd9cc38a7fcdd5e3bf/3.3.js\",\n\t\"/client/3ccd9cc38a7fcdd5e3bf/4.4.js\",\n\t\"/client/3ccd9cc38a7fcdd5e3bf/index.index.js\",\n\t\"/client/3ccd9cc38a7fcdd5e3bf/main.js\",\n\t\"/client/3ccd9cc38a7fcdd5e3bf/vendors~index.vendors~index.js\"\n];\n\nconst routes = [\n\t{ pattern: /^\\/$/ }\n];\n\n//# sourceURL=webpack:///./src/node_modules/@sapper/service-worker.js?");

/***/ }),

/***/ "./src/service-worker.ts":
/*!*******************************!*\
  !*** ./src/service-worker.ts ***!
  \*******************************/
/*! no exports provided */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _sapper_service_worker__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! @sapper/service-worker */ \"./src/node_modules/@sapper/service-worker.js\");\n\nconst ASSETS = `cache${_sapper_service_worker__WEBPACK_IMPORTED_MODULE_0__[\"timestamp\"]}`;\n// `shell` is an array of all the files generated by the bundler,\n// `files` is an array of everything in the `static` directory\nconst to_cache = _sapper_service_worker__WEBPACK_IMPORTED_MODULE_0__[\"shell\"].concat(_sapper_service_worker__WEBPACK_IMPORTED_MODULE_0__[\"files\"])\n    .filter(i => !i.startsWith('/videos'));\nconst staticAssets = new Set(to_cache);\nself.addEventListener('install', (event) => {\n    event.waitUntil(caches\n        .open(ASSETS)\n        .then(cache => cache.addAll(to_cache))\n        .then(() => {\n        self.skipWaiting();\n    }));\n});\nself.addEventListener('activate', (event) => {\n    event.waitUntil(caches.keys().then(async (keys) => {\n        // delete old caches\n        for (const key of keys) {\n            if (key !== ASSETS)\n                await caches.delete(key);\n        }\n        self.clients.claim();\n    }));\n});\n/**\n * Fetch the asset from the network and store it in the cache.\n * Fall back to the cache if the user is offline.\n */\nasync function fetchAndCache(request) {\n    const cache = await caches.open(`offline${_sapper_service_worker__WEBPACK_IMPORTED_MODULE_0__[\"timestamp\"]}`);\n    try {\n        const response = await fetch(request);\n        cache.put(request, response.clone());\n        return response;\n    }\n    catch (err) {\n        const response = await cache.match(request);\n        if (response)\n            return response;\n        throw err;\n    }\n}\nself.addEventListener('fetch', (event) => {\n    if (event.request.method !== 'GET' || event.request.headers.has('range'))\n        return;\n    const url = new URL(event.request.url);\n    // don't try to handle e.g. data: URIs\n    const isHttp = url.protocol.startsWith('http');\n    const isDevServerRequest = url.hostname === self.location.hostname && url.port !== self.location.port;\n    const isStaticAsset = url.host === self.location.host && staticAssets.has(url.pathname);\n    const skipBecauseUncached = event.request.cache === 'only-if-cached' && !isStaticAsset;\n    if (isHttp && !isDevServerRequest && !skipBecauseUncached) {\n        event.respondWith((async () => {\n            // always serve static files and bundler-generated style from cache.\n            // if your application has other URLs with data that will never change,\n            // set this variable to true for them and they will only be fetched once.\n            const cachedAsset = isStaticAsset && await caches.match(event.request);\n            // for pages, you might want to serve a shell `service-worker-index.html` file,\n            // which Sapper has generated for you. It's not right for every\n            // app, but if it's right for yours then uncomment this section\n            /*\n            if (!cachedAsset && url.origin === self.origin && routes.find(route => route.pattern.test(url.pathname))) {\n                return caches.match('/service-worker-index.html');\n            }\n            */\n            return cachedAsset || fetchAndCache(event.request);\n        })());\n    }\n});\n\n\n//# sourceURL=webpack:///./src/service-worker.ts?");

/***/ })

/******/ });